server:
  port: 8079
  servlet:
    contextPath: /secury
    sentry:
      dsn: https://b634809d661f4c4e97f9d1eadd794d48@o554395.ingest.sentry.io/5790885
spring:
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/secury?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 3141593
  mail:
    default-encoding: UTF-8
    host: smtp.mail.ru
    username: aliaga-82@mail.ru
    password: qarderob123
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
    servlet:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB

